server:
  port: 9404
spring:
  profiles:
    active: dev
  application:
    name: sentinel
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
#    sentinel:
            #            ##      transport:
          #          ##        dashboard: localhost:8080 #向sentinel控制台注册服务
          #          ##      eager: true #取消控制台懒加载